#!/bin/bash

if [ -n "$MANUAL" ]; then
  # if manual mode is enabled, just coast making supervisord happy
  while true; do
    sleep 60
  done
fi

# install node modules needed by the tests
cd /usr/src/app/projects/ngx-smart-popover
npm install
cd /usr/src/app
npm install

# check if Selenium server is listening @ port 4444
if nc -z localhost 4444; then
    
    npm run build:lib

    npm run e2e

    if [ $? -ne 0 ]; then
        supervisorctl signal SIGINT
    fi

    # shutdown supervisord, and in consequence the whole container
    supervisorctl shutdown
else
    # supervisord will execute this script again after services status changes
    # usually a single reload is enough to catch up with Selenium server
    echo "Selenium server is not available"
    exit 5
fi
